name: Alist-UN

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
        docker build -t alist-unlock:$IMAGE_TAG .
